// Generated by CoffeeScript 1.7.1
(function() {
  exports.index = function(req, res) {
    res.locals = {
      title: 'GPA Calculator',
      description: 'Calculate your GPA.'
    };
    return res.render('index');
  };

}).call(this);

//# sourceMappingURL=index.map
